# 1.1.4.1 Ensure separate partition exists for /var/tmp
- name: 1.1.4.1 Ensure separate partition exists for /var/tmp
  shell: findmnt --kernel /var/tmp
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('/var/tmp') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.1.4.1 Ensure separate partition exists for /var/tmp {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
