# 1.1.3.1 Ensure separate partition exists for /var

- name: set var
  set_fact:
    task_name: "Ensure separate partition exists for /var"
    task_id: "1.1.3.1"

- name: 1.1.3.1 Ensure separate partition exists for /var
  shell: findmnt --kernel /var
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('/var') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
