# 1.1.6.2 Ensure noexec option set on /var/log/audit partition
- name: 1.1.6.2 Ensure noexec option set on /var/log/audit partition
  shell: findmnt --kernel /var/log/audit | grep noexec
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('noexec') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.1.6.2 Ensure noexec option set on /var/log/audit partition {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
