# 1.1.8.1 Ensure /dev/shm is a separate partition
- name: 1.1.8.1 Ensure /dev/shm is a separate partition
  shell: findmnt --kernel /dev/shm
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('/dev/shm') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.1.8.1 Ensure /dev/shm is a separate partition {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
