# 1.1.7.1 Ensure separate partition exists for /home
- name: 1.1.7.1 Ensure separate partition exists for /home
  shell: findmnt --kernel /home
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('/home') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.1.7.1 Ensure separate partition exists for /home {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
