# 1.1.8.1 Ensure /dev/shm is a separate partition

- name: set var
  set_fact:
    task_name: "Ensure /dev/shm is a separate partition"
    task_id: "1.1.8.1"

- name: 1.1.8.1 Ensure /dev/shm is a separate partition
  shell: findmnt --kernel /dev/shm
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('/dev/shm') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
