# 1.1.7.3 Ensure nosuid option set on /home partition
- name: 1.1.7.3 Ensure nosuid option set on /home partition
  shell: findmnt --kernel /home | grep nosuid
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('nosuid') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.1.7.3 Ensure nosuid option set on /home partition {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
