# 1.5.3 Ensure core dump storage is disabled

- name: set var
  set_fact:
    task_name: "Ensure core dump storage is disabled"
    task_id: "1.5.3"

- name: 1.5.3 Ensure core dump storage is disabled
  shell: grep -i '^\s*storage\s*=\s*none' /etc/systemd/coredump.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('Storage=none') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
