# 1.5.4 Ensure core dump backtraces are disabled
- name: 1.5.4 Ensure core dump backtraces are disabled
  shell:  >-
    grep -Pi '^\h*ProcessSizeMax\h*=\h*0\b' /etc/systemd/coredump.conf ||
    echo -e "\n- Audit results:\n ** Fail **\n - \"ProcessSizeMax\" is: \"$(grep -i 'ProcessSizeMax' /etc/systemd/coredump.conf)\""


  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('ProcessSizeMax=0') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.5.4 Ensure core dump backtraces are disabled {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
