# 1.6.1.5 Ensure the SELinux mode is enforcing

- name: set var
  set_fact:
    task_name: "Ensure the SELinux mode is enforcing"
    task_id: "1.6.1.5"

- name: 1.6.1.5 Ensure the SELinux mode is enforcing
  shell: getenforce
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: "'Enforcing' in grep_result.stdout"

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
