# 1.6.1.7 Ensure SETroubleshoot is not installed
- name: 1.6.1.7 Ensure SETroubleshoot is not installed
  shell: rpm -q setroubleshoot
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('package setroubleshoot is not installed') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.6.1.7 Ensure SETroubleshoot is not installed {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
