# 1.6.1.2 Ensure SELinux is not disabled in bootloader configuration

- name: set var
  set_fact:
    task_name: "Ensure SELinux is not disabled in bootloader configuration"
    task_id: "1.6.1.2"

- name: 1.6.1.2 Ensure SELinux is not disabled in bootloader configuration
  shell: grubby --info=ALL | grep -Po '(selinux|enforcing)=0\b'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
