# 1.6.1.6 Ensure no unconfined services exist
- name: set var
  set_fact:
    task_name: "Ensure no unconfined services exist"
    task_id: "1.6.1.6"

- name: 1.6.1.6 Ensure no unconfined services exist
  shell: ps -eZ | grep unconfined_service_t
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout | length == 0

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
