# 1.7.5 Ensure permissions on /etc/issue are configured
- name: 1.7.5 Ensure permissions on /etc/issue are configured
  shell: stat -L /etc/issue
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('644') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.7.5 Ensure permissions on /etc/issue are configured {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
