# 2.1.2 Ensure chrony is configured
- name: 2.1.2 Ensure chrony is configured
  shell: grep -Pr -- '^\h*(server|pool)\h+[^#\n\r]+' /etc/chrony.d/
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('server') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.1.2 Ensure chrony is configured {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
