# 2.1.2 Ensure chrony is configured

- name: set var
  set_fact:
    task_name: "Ensure chrony is configured"
    task_id: "2.1.2"

- name: 2.1.2 Ensure chrony is configured
  shell: grep -Pr -- '^\h*(server|pool)\h+[^#\n\r]+' /etc/chrony.d/
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('server') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
