# 2.2.9 Ensure IMAP and POP3 server is not installed
- name: 2.2.9 Ensure IMAP and POP3 server is not installed
  shell: rpm -q dovecot cyrus-imapd
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'package dovecot is not installed' in grep_result.stdout or 'package cyrus-imapd is not installed' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.2.9 Ensure IMAP and POP3 server is not installed {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
