# 2.2.12 Ensure net-snmp is not installed or the snmpd service is not enabled
- name: 2.2.12 Ensure net-snmp is not installed or the snmpd service is not enabled
  shell: rpm -q net-snmp
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('package net-snmp is not installed') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.2.12 Ensure net-snmp is not installed or the snmpd service is not enabled  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

