# 2.2.8 Ensure a web server is not installed

- name: set var
  set_fact:
    task_name: "Ensure a web server is not installed"
    task_id: "2.2.8"

- name: 2.2.8 Ensure a web server is not installed
  shell: rpm -q httpd nginx
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: "'package httpd is not installed' in grep_result.stdout and 'package nginx is not installed' in grep_result.stdout"

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
