# 2.2.11 Ensure HTTP Proxy Server is not installed
- name: 2.2.11 Ensure HTTP Proxy Server is not installed
  shell: rpm -q squid
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('package squid is not installed') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.2.11 Ensure HTTP Proxy Server is not installed  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
