# 2.2.17 Ensure rpcbind is not installed or the rpcbind services are masked

- name: set var
  set_fact:
    task_name: "Ensure rpcbind is not installed or the rpcbind services are masked"
    task_id: "2.2.17"
 
- name: 2.2.17 Ensure rpcbind is not installed or the rpcbind services are masked
  shell: rpm -q rpcbind
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('package rpcbind is not installed') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
