# 2.2.3 Ensure a print server is not installed

- name: set var
  set_fact:
    task_name: "Ensure a print server is not installed"
    task_id: "2.2.3"

- name: 2.2.3 Ensure a print server is not installed
  shell: rpm -q cups
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('package cups is not installed') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
