# 2.2.15 Ensure mail transfer agent is configured for local-only mode
- name: 2.2.15 Ensure mail transfer agent is configured for local-only mode
  shell: ss -lntu | grep -P ':25\b' | grep -Pv '\h+(127\.0\.0\.1|\[?::1\]?):25\b'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.2.15 Ensure mail transfer agent is configured for local-only mode  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
