# 2.2.18 Ensure rsync-daemon is not installed or the rsyncd service is masked

- name: set var
  set_fact:
    task_name: "Ensure rsync-daemon is not installed or the rsyncd service is masked"
    task_id: "2.2.18"
 
- name: 2.2.18 Ensure rsync-daemon is not installed or the rsyncd service is masked
  shell: rpm -q rsync-daemon
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('package rsync-daemon is not installed') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
