# 2.2.8 Ensure a web server is not installed
- name: 2.2.8 Ensure a web server is not installed
  shell: rpm -q httpd nginx
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'package httpd is not installed' in grep_result.stdout or 'package nginx is not installed' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.2.8 Ensure a web server is not installed {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
