# 2.2.16 Ensure nfs-utils is not installed or the nfs-server service is masked

- name: set var
  set_fact:
    task_name: "Ensure nfs-utils is not installed or the nfs-server service is masked"
    task_id: "2.2.16"
 
- name: 2.2.16 Ensure nfs-utils is not installed or the nfs-server service is masked
  shell: rpm -q nfs-utils
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('package nfs-utils is not installed') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
