# 2.3.2 Ensure LDAP client is not installed
- name: 2.3.2 Ensure LDAP client is not installed
  shell: rpm -q openldap-clients
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('package openldap-clients is not installed') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.3.2 Ensure LDAP client is not installed  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
