# 3.4.1.1 Ensure nftables is installed
- name: 3.4.1.1 Ensure nftables is installed
  shell: rpm -q nftables
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.rc == 0

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "3.4.1.1 Ensure nftables is installed  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
