# 3.4.2.6 Ensure nftables established connections are configured

- name: set var
  set_fact:
    task_name: "Ensure nftables established connections are configured"
    task_id: "3.4.2.6"
 
- name: 3.4.2.6 Ensure nftables established connections are configured
  shell: systemctl is-enabled nftables.service | grep -q 'enabled' && nft list ruleset | awk '/hook input/,/}/' | grep 'ct state'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: "'ip protocol tcp ct state established accept' in grep_result.stdout or 'ip protocol udp ct state established accept' in grep_result.stdout or 'ip protocol icmp ct state established accept' in grep_result.stdout"

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""


