# 4.1.3 Ensure permissions on /etc/cron.hourly are configured
- name: Ensure permissions on /etc/cron.monthly are configured
  shell:  stat /etc/cron.hourly
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('700') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.1.3 Ensure permissions on /etc/cron.monthly are configured {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
