# 4.1.4 Ensure permissions on /etc/cron.daily are configured
- name: Ensure permissions on /etc/cron.daily are configured
  shell: stat /etc/cron.daily | grep 700
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('700') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.1.4 Ensure permissions on /etc/cron.daily are configured {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

