# 4.2.20 Ensure SSH Idle Timeout Interval is configured
- name: verify ClientAliveInterval is greater than zero
  shell:  sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep clientaliveinterval
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('15') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.2.20 Ensure SSH Idle Timeout Interval is configured (ClientAliveInterval) {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

- name: verify ClientAliveCountMax is greater than zero
  shell: sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep clientalivecountmax
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("3") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.2.20 Ensure SSH Idle Timeout Interval is configured (ClientAliveCountMax) {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

