# 4.2.19 Ensure SSH LoginGraceTime is set to one minute or less
- name: set var
  set_fact:
    task_name: "Ensure SSH LoginGraceTime is set to one minute or less"
    task_id: "4.2.19"

- name: 4.2.19 Ensure SSH LoginGraceTime is set to one minute or less
  shell: sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep LoginGraceTime
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: "'60' in grep_result.stdout"

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
