# 4.2.20 Ensure SSH Idle Timeout Interval is configured

- name: set var
  set_fact:
    task_name: "verify ClientAliveCountMax is greater than zero"
    task_id: "4.2.20.2"

- name: 4.2.20.2 verify ClientAliveCountMax is greater than zero
  shell: sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep clientalivecountmax
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find("3") != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
