# 4.2.14 Ensure system-wide crypto policy is not over-ridden
- name: set var
  set_fact:
    task_name: "Ensure system-wide crypto policy is not over-ridden"
    task_id: "4.2.14"

- name: 4.2.14 Ensure system-wide crypto policy is not over-ridden
  shell: grep -i '^\s*CRYPTO_POLICY=' /etc/sysconfig/sshd /etc/ssh/sshd_config.d/*.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find("") != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
