# 4.2.18 Ensure SSH MaxSessions is set to 10 or less
- name: Ensure SSH MaxSessions is set to 10 or less
  shell: sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep -i maxsessions
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'10' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.2.18 Ensure SSH MaxSessions is set to 10 or less {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
