# 4.2.1 Ensure permissions on /etc/ssh/sshd_config are configured
- name: set var
  set_fact:
    task_name: "Ensure permissions on /etc/ssh/sshd_config are configured"
    task_id: "4.2.1"

- name: 4.2.1 Ensure permissions on /etc/ssh/sshd_config are configured
  shell:  stat -Lc "%n %a %u/%U %g/%G" /etc/ssh/sshd_config
  register: grep_result
  ignore_errors: true

- name: Condition
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('600') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
