# 4.2.14 Ensure system-wide crypto policy is not over-ridden
- name: Ensure system-wide crypto policy is not over-ridden
  shell: grep -i '^\s*CRYPTO_POLICY=' /etc/sysconfig/sshd /etc/ssh/sshd_config.d/*.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.2.14 Ensure system-wide crypto policy is not over-ridden {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

