# 4.2.8 Ensure SSH HostbasedAuthentication is disabled 
- name: Ensure SSH HostbasedAuthentication is disabled
  shell: sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep hostbasedauthentication
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("no") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.2.8 Ensure SSH HostbasedAuthentication is disabled {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

