# 4.4.1 Ensure custom authselect profile is used
- name: set var
  set_fact:
    task_name: "Ensure custom authselect profile is used"
    task_id: "4.4.1"

- name: 4.4.1 Ensure custom authselect profile is used
  shell:  rpm -q authselect
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.rc == 0

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
