# 4.4.1 Ensure custom authselect profile is used
- name: Ensure custom authselect profile is used
  shell:  rpm -q authselect
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'version' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.4.1 Ensure custom authselect profile is used {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

