---
# 4.5.1 Ensure password creation requirements are configured
- name: set var
  set_fact:
    task_name: "Ensure password creation requirements are configured"
    task_id: "4.5.1"

- name: 4.5.1 Check minimum password length requirement in PAM configuration
  shell: cat /etc/security/pwquality.conf |  grep  "minlen = 14"
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.rc == 0 and grep_result.stdout != ''

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
