# 4.5.4 Ensure password hashing algorithm is SHA-512
- name: Ensure password hashing algorithm is SHA-512
  shell: grep -Ei '^\s*crypt_style\s*=\s*(sha512|yescrypt)\b' /etc/libuser.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("sha512") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.5.4 Ensure password hashing algorithm is SHA-512  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"


