---
# 4.5.1 Ensure password creation requirements are configured
- name: Check minimum password length requirement in PAM configuration
  shell: cat /etc/security/pwquality.conf |  grep  "minlen = 14"
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.rc == 0 and grep_result.stdout != ''

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.5.1 Ensure password creation requirements are configured {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

