- name: Ensure default group for the root account is GID 0
  shell: 'grep "^root:" /etc/passwd | cut -f4 -d:'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('0') != -1

- name: Save result in file
  lineinfile:
    path: "{{ Result_path }}"
    line: "4.6.4 Ensure default group for the root account is GID 0 {{ tasks_status }}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

