# 4.6.1.1 Ensure password expiration is 365 days or less
- name: Ensure password expiration is 365 days or less
  shell: grep -E '^\s*PASS_MAX_DAYS\s+[0-9]+' /etc/login.defs | awk '{print $2}'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "{{ 'Passed' if grep_result.stdout | int(default=0) <= 365 else 'Failed' }}"
  when: grep_result.rc == 0

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.6.1.1 Ensure password expiration is 365 days or less  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

