# 4.6.6 Ensure root password is set
- name: Ensure root password is set
  shell: passwd -S root
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("Password set") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.6.6 Ensure root password is set  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

