# 4.6.1.4 Ensure inactive password lock is 30 days or less

- name: set var
  set_fact:
    task_name: "Ensure inactive password lock is 30 days or less"
    task_id: "4.6.1.4"
 
- name: 4.6.1.4 Ensure inactive password lock is 30 days or less
  shell: useradd -D | grep INACTIVE
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "{{ 'Passed' if (grep_result.stdout | regex_search('^INACTIVE=([0-9]+)$', '\\1') | int(default=0)) <= 30 and (grep_result.stdout | regex_search('^INACTIVE=-1$')) == None else 'Failed' }}"
  when: grep_result.stdout != ""

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""

