# 4.6.1.3 Ensure password expiration warning days is 7 or more

- name: set var
  set_fact:
    task_name: "Ensure password expiration warning days is 7 or more"
    task_id: "4.6.1.3"
 
- name: 4.6.1.3 Ensure password expiration warning days is 7 or more
  shell: grep PASS_WARN_AGE /etc/login.defs
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find("7") != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""

