# 4.6.4 Ensure default group for the root account is GID 0

- name: set var
  set_fact:
    task_name: "Ensure default group for the root account is GID 0"
    task_id: "4.6.4"

- name: 4.6.4 Ensure default group for the root account is GID 0
  shell: 'grep "^root:" /etc/passwd | cut -f4 -d:'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('0') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"
 
- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""

