# 5.1.1.4 Ensure rsyslog default file permissions are configured
- name: Ensure rsyslog default file permissions are configured
  shell: grep ^\s*ForwardToSyslog /etc/systemd/journald.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("0640") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.1.1.3 Ensure journald is configured to send logs to rsyslog  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

