# 5.1.1.1 Ensure rsyslog is installed
- name: Ensure rsyslog is installed
  command: rpm -q rsyslog
  register: rpm_result
  ignore_errors: true

- name: Set tasks_status to Passed
  set_fact:
    tasks_status: "[Passed]"
  when: rpm_result.stdout != "package rsyslog is not installed"

- name: Set tasks_status to Failed
  set_fact:
    tasks_status: "[Failed]"
  when: rpm_result.stdout == "package rsyslog is not installed"

- name: Save result in file
  lineinfile:
    path: "{{ Result_path }}"
    line: "5.1.1.1 Ensure rsyslog is installed  {{ tasks_status }}"
  delegate_to: localhost

