# 5.1.1.7 Ensure rsyslog is not configured to receive logs from a remote client
- name: set var
  set_fact:
    task_name: "Ensure rsyslog is not configured to receive logs from a remote client"
    task_id: "5.1.1.7"

- name: 5.1.1.7 Ensure rsyslog is not configured to receive logs from a remote client
  shell: grep -Ps -- '^\h*module\(load="imtcp"\)' /etc/rsyslog.conf /etc/rsyslog.d/*.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find("") != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
