# 5.1.1.2 Ensure rsyslog service is enabled
- name: Ensure rsyslog service is enabled
  shell: systemctl is-enabled rsyslog
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("enabled") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.1.1.2 Ensure rsyslog service is enabled  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"


