# 5.2.1.4 Ensure auditd service is enabled
- name: set var
  set_fact:
    task_name: "Ensure auditd service is enabled"
    task_id: "5.2.1.4"

- name: 5.2.1.4 Ensure auditd service is enabled
  shell:  systemctl is-enabled auditd
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('enabled') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
