# 5.2.4.5 Ensure audit configuration files are 640 or more restrictive
- name: set var
  set_fact:
    task_name: "Ensure audit configuration files are 640 or more restrictive"
    task_id: "5.2.4.5"

- name: 5.2.4.5 Ensure audit configuration files are 640 or more restrictive
  shell: find /etc/audit/ -type f \( -name '*.conf' -o -name '*.rules' \) -exec stat -Lc "%n %a" {} + | grep -Pv -- '^\h*\H+\h*([0,2,4,6][0,4]0)\h*$'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout == ""

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
