# 5.2.4.1 Ensure audit log files are mode 0640 or less permissive
- name: set var
  set_fact:
    task_name: "Ensure audit log files are mode 0640 or less permissive"
    task_id: "5.2.4.1"

- name: 5.2.4.1 Ensure audit log files are mode 0640 or less permissive
  shell: '[ -f /etc/audit/auditd.conf ] && find "$(dirname $(awk -F "=" "/^\\s*log_file/ {print \$2}" /etc/audit/auditd.conf | xargs))" -type f \( ! -perm 600 -a ! -perm 0400 -a ! -perm 0200 -a ! -perm 0000 -a ! -perm 0640 -a ! -perm 0440 -a ! -perm 0040 \) -exec stat -Lc "%n %#a" {} +'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout == ""

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
