# 5.2.4.2 Ensure only authorized users own audit log files
- name: set var
  set_fact:
    task_name: "Ensure only authorized users own audit log files"
    task_id: "5.2.4.2"

- name: 5.2.4.2 Ensure only authorized users own audit log files
  shell: >
    [ -f /etc/audit/auditd.conf ] &&
    find "$(dirname $(awk -F "=" '/^\s*log_file/ {print $2}' /etc/audit/auditd.conf | xargs))" -type f ! -user root -exec stat -Lc "%n %U" {} +
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout == ""

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
