# 5.2.2.1 Ensure audit log storage size is configured
- name: Ensure audit log storage size is configured
  shell: grep -w "^\s*max_log_file\s*=" /etc/audit/auditd.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'max_log_file = ' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.2.2.1 Ensure audit log storage size is configured  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"


