# 5.2.2.2 Ensure audit logs are not automatically deleted
- name: set var
  set_fact:
    task_name: "Ensure audit logs are not automatically deleted"
    task_id: "5.2.2.2"

- name: 5.2.2.2 Ensure audit logs are not automatically deleted
  shell: grep max_log_file_action /etc/audit/auditd.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: "'max_log_file_action = keep_logs' in grep_result.stdout"

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
