# 5.2.4.3 Ensure only authorized groups are assigned ownership of audit log files
- name: Ensure only authorized groups are assigned ownership of audit log files
  shell: grep -Piw -- '^\h*log_group\h*=\h*(adm|root)\b' /etc/audit/auditd.conf
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout | regex_search('adm|root')

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.2.4.3 Ensure only authorized groups are assigned ownership of audit log files {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"


