# 5.2.1.2 Ensure auditing for processes that start prior to auditd is enabled
- name: Ensure auditing for processes that start prior to auditd is enabled
  shell: grubby --info=ALL | grep -Po '\baudit=1\b'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("audit=1") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.2.1.2 Ensure auditing for processes that start prior to auditd is enabled  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"


