# 5.2.4.6 Ensure audit configuration files are owned by root
- name: set var
  set_fact:
    task_name: "Ensure audit configuration files are owned by root"
    task_id: "5.2.4.6"

- name: 5.2.4.6 Ensure audit configuration files are owned by root
  shell: find /etc/audit/ -type f \( -name '*.conf' -o -name '*.rules' \) ! -user root
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout == ""

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
