# 5.2.4.7 Ensure audit configuration files belong to group root
- name: Ensure audit configuration files belong to group root
  shell: find /etc/audit/ -type f \( -name '*.conf' -o -name '*.rules' \) ! -group root
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout == ""

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.2.4.7 Ensure audit configuration files belong to group root {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"



