# 5.2.4.4 Ensure the audit log directory is 0750 or more restrictive
- name: Ensure the audit log directory is 0750 or more restrictive
  shell: stat -Lc "%n %a" "$(dirname $( awk -F"=" '/^\s*log_file\s*=\s*/ {print $2}' /etc/audit/auditd.conf))" | grep -Pv -- '^\h*\H+\h+([0,5,7][0,5]0)'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout == ""

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.2.4.4 Ensure the audit log directory is 0750 or more restrictive {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"


