# 5.2.4.4 Ensure the audit log directory is 0750 or more restrictive
- name: set var
  set_fact:
    task_name: "Ensure the audit log directory is 0750 or more restrictive"
    task_id: "5.2.4.4"

- name: 5.2.4.4 Ensure the audit log directory is 0750 or more restrictive
  shell: stat -Lc "%n %a" "$(dirname $( awk -F"=" '/^\s*log_file\s*=\s*/ {print $2}' /etc/audit/auditd.conf))" | grep -Pv -- '^\h*\H+\h+([0,5,7][0,5]0)'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout == ""

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
