# 5.2.1.1 Ensure auditd is installed
- name: set var
  set_fact:
    task_name: "Ensure auditd is installed"
    task_id: "5.2.1.1"

- name: 5.2.1.1 Ensure auditd is installed
  command: rpm -q audit
  register: rpm_result
  ignore_errors: true

- name: Set tasks_status to Passed
  set_fact:
    tasks_status: "Passed"
  when: rpm_result.stdout != "package audit is not installed"

- name: Set tasks_status to Failed
  set_fact:
    tasks_status: "Failed"
  when: rpm_result.stdout == "package audit is not installed"

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
