# 6.2.2 Ensure /etc/shadow password fields are not empty
- name: set var
  set_fact:
    task_name: "Ensure /etc/shadow password fields are not empty"
    task_id: "6.2.2"

- name: 6.2.2 Ensure /etc/shadow password fields are not empty
  shell: 'awk -F: "($2 == \"\") { print $1 \" does not have a password \" }" /etc/shadow'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
