# 6.2.5 Ensure no duplicate GIDs exist
- name: set var
  set_fact:
    task_name: "Ensure no duplicate GIDs exist"
    task_id: "6.2.5"

- name: 6.2.5 Ensure no duplicate GIDs exist
  shell: |
        cut -d: -f3 /etc/group | sort | uniq -d | while read x ; do
          echo "Duplicate GID ($x) in /etc/group"
        done
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
