# 6.2.4 Ensure no duplicate UIDs exist
- name: set var
  set_fact:
    task_name: "Ensure no duplicate UIDs exist"
    task_id: "6.2.4"

- name: 6.2.4 Ensure no duplicate UIDs exist
  shell: |
        cut -f3 -d":" /etc/passwd | sort -n | uniq -c | while read x ; do
          [ -z "$x" ] && break
          set - $x
          if [ $1 -gt 1 ]; then
            users=$(awk -F: '($3 == n) { print $1 }' n=$2 /etc/passwd | xargs)
            echo "Duplicate UID ($2): $users"
          fi
        done
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('') != -1


- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
