# 6.2.8 Ensure root PATH Integrity
- name: set var
  set_fact:
    task_name: "Ensure root PATH Integrity"
    task_id: "6.2.8"

- name: 6.2.8 Ensure root PATH Integrity
  shell: |
        RPCV="$(sudo -Hiu root env | grep '^PATH' | cut -d= -f2)"
        echo "$RPCV" | grep -q "::" && echo "root's path contains a empty directory
        (::)"
        echo "$RPCV" | grep -q ":$" && echo "root's path contains a trailing (:)"
        for x in $(echo "$RPCV" | tr ":" " "); do
          if [ -d "$x" ]; then
            ls -ldH "$x" | awk '$9 == "." {print "PATH contains current working
        directory (.)"}
            $3 != "root" {print $9, "is not owned by root"}
            substr($1,6,1) != "-" {print $9, "is group writable"}
            substr($1,9,1) != "-" {print $9, "is world writable"}'
          else
            echo "$x is not a directory"
          fi
        done
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('') != -1


- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
