# 6.2.1 Ensure accounts in /etc/passwd use shadowed passwords
- name: set var
  set_fact:
    task_name: "Ensure accounts in /etc/passwd use shadowed passwords"
    task_id: "6.2.1"

- name: 6.2.1 Ensure accounts in /etc/passwd use shadowed passwords
  shell: "awk -F: '($2 != \"x\" ) { print $1 \" is not set to shadowed passwords \"}' /etc/passwd"
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.stdout.find('') != -1

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
