# 6.2.1 Ensure accounts in /etc/passwd use shadowed passwords
- name: 6.2.1 Ensure accounts in /etc/passwd use shadowed passwords
  shell: "awk -F: '($2 != \"x\" ) { print $1 \" is not set to shadowed passwords \"}' /etc/passwd"
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "6.2.1 Ensure accounts in /etc/passwd use shadowed passwords {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
