# 1.3.1 Ensure AIDE is installed
- name: set var
  set_fact:
    task_name: "Ensure is installed"
    task_id: "1.3.2"
    
- name: 1.3.1 Ensure AIDE is installed
  shell: rpm -q aide
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.rc == 0

- name: Add result to task_results
  set_fact:
    task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_name': task_name, 'tasks_status': tasks_status}] }}"

- name: unset var
  set_fact:
    tasks_status: "Failed"
    task_name: ""
    task_id: ""
