# 1.3.1 Ensure AIDE is installed
- name: set var
  set_fact:
    task_names: "Ensure AIDE is installed"
    task_id: "1.3.1"
    tasks_status: "Failed"
    
- name: 1.3.1 Ensure AIDE is installed
  shell: rpm -q aide
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "Passed"
  when: grep_result.rc == 0

- name: Append result to the list
  set_fact:
   task_results: "{{ task_results | default([]) + [{'task_id': task_id, 'task_names': task_names, 'tasks_status': (grep_result.rc == 0) | ternary('[Passed]', 'Failed')}] }}"

