 - name: Ansible playbook for CIS hardening
   hosts: demo
   become: yes
   roles:
    - Audit
  # - Remediate

   tasks:
    - name: Save results to the CSV file
      template:
        src: /home/ansible/CIS-main/roles/Audit/template/result_template.j2  # Path to your Jinja2 template file
        dest: "{{ csv_output_path }}.{{ ansible_hostname }}.csv"   # Path where you want to save the CSV file
      delegate_to: localhost
