 - name: Ansible playbook for CIS hardening
   hosts: demo
   become: yes
   tasks:
    - name: Set CSV Output Path
      set_fact:
        csv_output_path: "{{ csv_output_path }}"
   roles:
    - Audit
      # - Remediate
