# 2.2.17 Ensure rpcbind is not installed or the rpcbind services are masked
- name: 2.2.17 Ensure rpcbind is not installed or the rpcbind services are masked
  shell: rpm -q nfs-utils
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('package nfs-utils is not installed') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "2.2.17 Ensure rpcbind is not installed or the rpcbind services are masked  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
