# 3.4.2.6 Ensure nftables established connections are configured
- name: 3.4.2.6 Ensure nftables established connections are configured
  shell: systemctl is-enabled nftables.service | grep -q 'enabled' && nft list ruleset | awk '/hook input/,/}/' | grep 'ct state'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'ip protocol tcp ct state established accept' in grep_result.stdout or 'ip protocol udp ct state established accept' in grep_result.stdout or 'ip protocol icmp ct state established accept' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "3.4.2.6 Ensure nftables established connections are configured {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
