# 4.2.6 Ensure SSH PAM is enabled
- name: Ensure SSH PAM is enabled
  shell: sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep -i usepam
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("yes") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.2.6 Ensure SSH PAM is enabled {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

