- name: Ensure SSH LoginGraceTime is set to one minute or less
  shell: sshd -T -C user=root -C host="$(hostname)" -C addr="$(grep $(hostname) /etc/hosts | awk '{print $1}')" | grep LoginGraceTime
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'60' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.2.19 Ensure SSH LoginGraceTime is set to one minute or less {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

