# 5.2.4.8 Ensure audit tools are 755 or more restrictive
- name: Ensure audit tools are 755 or more restrictive
  shell: stat -c "%n %a" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules | grep -Pv -- '^\h*\H+\h+([0-7][0,1,4,5][0,1,4,5])\h*$'
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout == ""

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "5.2.4.8 Ensure audit tools are 755 or more restrictive {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"

