# 1.1.3.1 Ensure separate partition exists for /var
- name: 1.1.3.1 Ensure separate partition exists for /var
  shell: findmnt --kernel /var
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('/var') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.1.3.1 Ensure separate partition exists for /var {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
