# 1.1.2.1 Ensure /tmp is a separate partition
- name: 1.1.2.1 Ensure /tmp is a separate partition
  shell: findmnt -nk /tmp
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find('/tmp') != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.1.2.1 Ensure /tmp is a separate partition {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
