# 1.6.1.4 Ensure the SELinux mode is not disabled
- name: 1.6.1.4 Ensure the SELinux mode is not disabled
  lineinfile:
   path: /etc/selinux/config
   regexp: '^(?i)#?\s*SELINUX\s*=' # '^': This symbol indicates the beginning of a line.
                                   # '(?i)':It means that the regular expression will match the pattern regardless of whether the letters are uppercase or lowercase.                                   # #?: This part matches an optional # character (used for commenting out settings).
                                   # The ? symbol means that the # character may or may not be present.
   line: 'SELINUX=enforcing'
