# 1.6.1.5 Ensure the SELinux mode is enforcing
- name: 1.6.1.5 Ensure the SELinux mode is enforcing
  shell: getenforce
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: "'Enforcing' in grep_result.stdout"

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "1.6.1.5 Ensure the SELinux mode is enforcing {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"
