# 4.6.1.3 Ensure password expiration warning days is 7 or more
- name: Ensure password expiration warning days is 7 or more
  lineinfile:
   path: /etc/login.defs
   regexp: '^(?i)#?\s*PASS_WARN_AGE='
                                   # '^': This symbol indicates the beginning of a line.
                                   # '(?i)':It means that the regular expression will match the pattern regardless of whether the letters are uppercase or lowercase.                                   # #?: This part matches an optional # character (used for commenting out settings).
                                   # The ? symbol means that the # character may or may not be present.
   line: 'PASS_WARN_AGE=7'
