# 4.6.1.3 Ensure password expiration warning days is 7 or more
- name: Ensure password expiration warning days is 7 or more
  shell: grep PASS_WARN_AGE /etc/login.defs
  register: grep_result
  ignore_errors: true

- name: Display
  set_fact:
    tasks_status: "[Passed]"
  when: grep_result.stdout.find("7") != -1

- name: Save result in file
  lineinfile:
    path: "{{Result_path}}"
    line: "4.6.1.3 Ensure password expiration warning days is 7 or more  {{tasks_status}}"
  delegate_to: localhost

- name: unset var
  set_fact:
    tasks_status: "[Failed]"


