# 4.6.1.1 Ensure password expiration is 365 days or less
- name: 4.6.1.1 Ensure password expiration is 365 days or less
  lineinfile:
   path: /etc/login.defs
   regexp: '^(?i)#?\s*PASS_MAX_DAYS='
           
                                   # '^': This symbol indicates the beginning of a line.
                                   # '(?i)':It means that the regular expression will match the pattern regardless of whether the letters are uppercase or lowercase.                                   # #?: This part matches an optional # character (used for commenting out settings).
                                   # The ? symbol means that the # character may or may not be present.
                                   # \d+: This part of the regular expression matches one or more digit characters (0-9).
                                   # \s+: This matches one or more whitespace characters. It ensures that there is at least one space or tab after "ENCRYPT_METHOD."
   line: 'PASS_MAX_DAYS=365'
