# 6.1.6 Ensure permissions on /etc/shadow are configured
- name: 6.1.6 Remove excess permissions on /etc/shadow
  file:
    path: /etc/shadow
    mode: '0000'

- name: 6.1.6 Set owner and group on /etc/shadow
  file:
    path: /etc/shadow
    owner: root
    group: root
