# 6.1.4 Ensure permissions on /etc/group are configured
- name: 6.1.4 Remove excess permissions on /etc/group
  file:
    path: /etc/group
    mode: '0644'

- name: 6.1.4 Set owner and group on /etc/group
  file:
    path: /etc/group
    owner: root
    group: root
