# 6.2.1 Ensure accounts in /etc/passwd use shadowed passwords
- name: 6.2.1 Ensure accounts in /etc/passwd use shadowed passwords
  command: sed -e 's/^\([a-zA-Z0-9_]*\):[^:]*:/\1:x:/' -i /etc/passwd
